# Generated by Django 4.0.4 on 2022-11-03 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('permissao_01', 'Permite acessar a view Teste'), ('permissao_02', 'Permite visualizar um botão na página')]},
        ),
    ]
